version: '3.8'

services:
  streamlit-app:
    image: sjayaprakash/shreevari-mart:latest 
    container_name: streamlit-app
    restart: always
    depends_on:
      - mongodb
    networks:
      - mynetwork
    ports:
      - "8501:8501"
    environment:
      - MONGO_HOST=mongodb  
